#!/usr/bin/env bash
# this is specific to knot's setup, but should give an idea of how to build it
./gradlew build
./gradlew modShadowJar
cp /home/dragon/Development/Knot/bta-discord/build/libs/discord-*-mod.jar /home/dragon/Downloads/bta_fabric_server_7.3_04/mods/